### ISSUE TITLE
GCC builtin __builtin_unreachable needs including in CIL builtin functions

### ISSUE THREAD

**Issue by ctshepherd** [kerneis/cpc#11]
CC    x86_64-softmmu/target-i386/translate.o
/home/cs648/qemu/tcg/tcg-op.h:2165: Warning: Calling function __builtin_unreachable without prototype.

I'm not sure if it's worth including the semantics of __builtin_unreachable(), but it should be added to the builtin function list at the least.

**Comment by kerneis** [comment]
Fixed in CIL https://github.com/kerneis/cil/commit/607e5b5a28d7166240fb2f0a9ede17817edbe802 and cherry-picked in CPC. Thanks.
