### ISSUE TITLE
Unknown flexlink "-g" option when compiling under cygwin.

### ISSUE THREAD

**Issue by boutier** [kerneis/cpc#6]
Compilation of the "windows-aio" branch of cpc fail under cygwin, due to an unrecognize -g option for flexlink.  A similar problem appeared for CIL:

```
http://www.mail-archive.com/cil-users@lists.sourceforge.net/msg00383.html
```

Remark than now, ocamlutil/Makefile.ocaml doesn't exists anymore in the CIL repository, but still exists in the CPC repository.

Here are the log of the failed compilation of CPC:

```
http://pastebin.com/YtHpRnUd
```

and the successful one of CIL:

```
http://pastebin.com/mPcbLxW4
```

**Comment by kerneis** [comment]
I need to rebase this branch against develop. Thanks for the report.

**Comment by kerneis** [comment]
Done.
