### ISSUE TITLE
Problem with GCC builtins

### ISSUE THREAD

**Issue by ctshepherd** [kerneis/cpc#7]
While working on QEMU I've noticed a problematic interaction between GCC builtins and CPC.

I think the problem lies with CIL rather than CPC. GCC builtins have no prototypes, so CIL inserts a default prototype. GCC then sees the prototype in the source file and decides this means the builtin function shouldn't be used.

Unfortunately I'm not sure what the best solution to this is. I don't know if GCC's behaviour is very standard compliant.

A minimal example (__atomic_thread_fence is a GCC builtin used in QEMU):
http://codepad.org/lDgazDSD

Test:
http://codepad.org/TawMay3B

**Comment by kerneis** [comment]
This is indeed a bug in CIL. GCC builtins need to be added to CIL, and recent
ones are not: see the hashtable [builtinFunctions] in src/cil.ml. Adding more is
trivial, at least for the simple ones that do not play dark magic with C types.
you just need to express their prototype in CIL's type system, and mimic the way
the existing ones are added to the table. Nothing more needs to be done.

Do not hesitate to provide a patch (see
http://kerneis.github.io/cil/doc/html/cil/api/Cil.html#TYPEtyp for the
constructors that CIL uses to represent C types), or at least a list of the
missing builtins and their prototype.

**Comment by kerneis** [comment]
Fixed in CIL, will be fixed in CPC on the next merge. Thanks.

https://github.com/kerneis/cil/commit/acb7f9d3f8175eb069bed5a0b46255cc7441905f (agnostic handling of "overloaded")
https://github.com/kerneis/cil/commit/ac5fd5219253ec3010f75cfbf127ee2e8b23bc9e (your patch with minor fixes)
